export const GET_WORKSPACES = "GET_WORKSPACES"
export const GET_WORKSPACES_SUCCESS = "GET_WORKSPACES_SUCCESS"
export const GET_WORKSPACES_FAIL = "GET_WORKSPACES_FAIL"

export const GET_WORKSPACE_DETAIL = "GET_WORKSPACE_DETAIL"
export const GET_WORKSPACE_DETAIL_SUCCESS = "GET_WORKSPACE_DETAIL_SUCCESS"
export const GET_WORKSPACE_DETAIL_FAIL = "GET_WORKSPACE_DETAIL_FAIL"
