version: '3.8'

services:
  test-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    restart: on-failure
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_APP_DEFAULTAUTH=jwt
      - NODE_ENV=development
      - VITE_ENV=development
      - VITE_API_DEV_URL=https://notifyapi.ozgurkurul.com.tr
      - VITE_API_PROD_URL=https://notifyapi.ozgurkurul.com.tr
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"