export const GET_DASHBOARDS = "GET_DASHBOARDS"
export const GET_DASHBOARDS_SUCCESS = "GET_DASHBOARDS_SUCCESS"
export const GET_DASHBOARDS_FAIL = "GET_DASHBOARDS_FAIL"

export const GET_DASHBOARD_DETAIL = "GET_DASHBOARD_DETAIL"
export const GET_DASHBOARD_DETAIL_SUCCESS = "GET_DASHBOARD_DETAIL_SUCCESS"
export const GET_DASHBOARD_DETAIL_FAIL = "GET_DASHBOARD_DETAIL_FAIL"

export const GET_DASHBOARD_DETAIL_KANBAN = "GET_DASHBOARD_DETAIL_KANBAN"
export const GET_DASHBOARD_DETAIL_KANBAN_SUCCESS = "GET_DASHBOARD_DETAIL_KANBAN_SUCCESS"
export const GET_DASHBOARD_DETAIL_KANBAN_FAIL = "GET_DASHBOARD_DETAIL_KANBAN_FAIL"